//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentAttendanceManagementSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class StaffStandard
    {
        public int StaffID { get; set; }
        public int StandardID { get; set; }
        public int SubjectID { get; set; }
        public int StaffStandard1 { get; set; }
    
        public virtual Standard Standard { get; set; }
        public virtual Subject Subject { get; set; }
    }
}
