//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Complaint
    {
        public int ComplaintID { get; set; }
        public int StudentID { get; set; }
        public string Subject { get; set; }
        public string Message { get; set; }
        public System.DateTime Date { get; set; }
    
        public virtual Student Student { get; set; }
    }
}
