//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class StaffStandard
    {
        public int StaffID { get; set; }
        public int StanadardID { get; set; }
        public int SubjectID { get; set; }
        public int StaffStandardID { get; set; }
    
        public virtual Standard Standard { get; set; }
        public virtual Subject Subject { get; set; }
    }
}
