//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Standard
    {
        public Standard()
        {
            this.Divisions = new HashSet<Division>();
            this.StaffStandards = new HashSet<StaffStandard>();
            this.Students = new HashSet<Student>();
        }
    
        public int StandardID { get; set; }
        public string StandardName { get; set; }
    
        public virtual ICollection<Division> Divisions { get; set; }
        public virtual ICollection<StaffStandard> StaffStandards { get; set; }
        public virtual ICollection<Student> Students { get; set; }
    }
}
