//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Student
    {
        public int StudentID { get; set; }
        public int RollNo { get; set; }
        public string StudentName { get; set; }
        public string DivisionName { get; set; }
        public string StudentEmail { get; set; }
        public string StudentMobile { get; set; }
        public System.DateTime DOB { get; set; }
        public string Image { get; set; }
        public string StudentAddress { get; set; }
        public string StudentCity { get; set; }
        public int StudentPincode { get; set; }
        public string StudentUsername { get; set; }
        public string StudentPassword { get; set; }
        public string StandardName { get; set; }
        public string Gender { get; set; }
        public int RoleID { get; set; }
    }
}
